/* Generated by Yosys 0.69+post (git sha1 143eb14f9cc55d6f8927e68523b0c9d2166ed02c, Release, AppleClang clang++ 21.0.0.21000334) */

module pixel_pwm(clk, rst, duty, enable, pwm);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [8:0] duty;
  wire [8:0] duty;
  input enable;
  wire enable;
  output pwm;
  wire pwm;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire [8:0] active_duty;
  wire active_enable;
  wire [7:0] counter;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _076_ (
    .I(active_duty[1]),
    .ZN(_039_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _077_ (
    .I(active_duty[4]),
    .ZN(_040_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _078_ (
    .I(counter[3]),
    .ZN(_041_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _079_ (
    .I(rst),
    .ZN(_042_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _080_ (
    .A1(counter[0]),
    .A2(counter[1]),
    .ZN(_043_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _081_ (
    .A1(counter[0]),
    .A2(counter[2]),
    .A3(counter[1]),
    .ZN(_044_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _082_ (
    .A1(_041_),
    .A2(_044_),
    .ZN(_045_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _083_ (
    .A1(counter[4]),
    .A2(_045_),
    .ZN(_046_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _084_ (
    .A1(counter[5]),
    .A2(counter[4]),
    .A3(_045_),
    .ZN(_047_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _085_ (
    .A1(counter[5]),
    .A2(counter[4]),
    .A3(counter[6]),
    .A4(_045_),
    .ZN(_048_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _086_ (
    .I(_048_),
    .ZN(_049_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _087_ (
    .A1(counter[6]),
    .A2(_047_),
    .Z(_050_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _088_ (
    .A1(_042_),
    .A2(_050_),
    .ZN(_000_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _089_ (
    .A1(counter[5]),
    .A2(_046_),
    .Z(_051_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _090_ (
    .A1(_042_),
    .A2(_051_),
    .ZN(_001_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _091_ (
    .A1(counter[4]),
    .A2(_045_),
    .Z(_052_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _092_ (
    .A1(rst),
    .A2(_052_),
    .Z(_002_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _093_ (
    .A1(counter[3]),
    .A2(_044_),
    .Z(_053_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _094_ (
    .A1(_042_),
    .A2(_053_),
    .ZN(_003_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _095_ (
    .A1(counter[2]),
    .A2(_043_),
    .Z(_054_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _096_ (
    .A1(_042_),
    .A2(_054_),
    .ZN(_004_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _097_ (
    .A1(counter[0]),
    .A2(counter[1]),
    .Z(_055_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _098_ (
    .A1(rst),
    .A2(_055_),
    .Z(_005_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _099_ (
    .A1(counter[0]),
    .A2(_042_),
    .ZN(_006_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _100_ (
    .A1(counter[7]),
    .A2(_049_),
    .Z(_056_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _101_ (
    .A1(counter[7]),
    .A2(_049_),
    .ZN(_057_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _102_ (
    .A1(active_duty[7]),
    .A2(_057_),
    .ZN(_058_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _103_ (
    .A1(duty[3]),
    .A2(duty[2]),
    .A3(duty[1]),
    .A4(duty[0]),
    .ZN(_059_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _104_ (
    .A1(duty[7]),
    .A2(duty[6]),
    .A3(duty[5]),
    .A4(duty[4]),
    .ZN(_060_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _105_ (
    .A1(_059_),
    .A2(_060_),
    .ZN(_061_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _106_ (
    .A1(duty[8]),
    .A2(_061_),
    .ZN(_062_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _107_ (
    .A1(duty[7]),
    .A2(_056_),
    .A3(_062_),
    .ZN(_063_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _108_ (
    .A1(_058_),
    .A2(_063_),
    .B(rst),
    .ZN(_007_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _109_ (
    .A1(active_duty[6]),
    .A2(_057_),
    .ZN(_064_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _110_ (
    .A1(duty[6]),
    .A2(_056_),
    .A3(_062_),
    .ZN(_065_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _111_ (
    .A1(_064_),
    .A2(_065_),
    .B(rst),
    .ZN(_008_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _112_ (
    .A1(active_duty[5]),
    .A2(_057_),
    .ZN(_066_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _113_ (
    .A1(duty[5]),
    .A2(_056_),
    .A3(_062_),
    .ZN(_067_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _114_ (
    .A1(_066_),
    .A2(_067_),
    .B(rst),
    .ZN(_009_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _115_ (
    .A1(duty[4]),
    .A2(_062_),
    .B(_057_),
    .ZN(_068_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _116_ (
    .A1(_040_),
    .A2(_057_),
    .B(_068_),
    .C(rst),
    .ZN(_010_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _117_ (
    .A1(active_duty[3]),
    .A2(_057_),
    .ZN(_069_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _118_ (
    .A1(duty[3]),
    .A2(_056_),
    .A3(_062_),
    .ZN(_070_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _119_ (
    .A1(_069_),
    .A2(_070_),
    .B(rst),
    .ZN(_011_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _120_ (
    .A1(active_duty[2]),
    .A2(_057_),
    .ZN(_071_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _121_ (
    .A1(duty[2]),
    .A2(_056_),
    .A3(_062_),
    .ZN(_072_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _122_ (
    .A1(_071_),
    .A2(_072_),
    .B(rst),
    .ZN(_012_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _123_ (
    .A1(duty[8]),
    .A2(_057_),
    .ZN(_073_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _124_ (
    .A1(active_duty[1]),
    .A2(_057_),
    .B1(_073_),
    .B2(duty[1]),
    .ZN(_074_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _125_ (
    .A1(rst),
    .A2(_074_),
    .ZN(_013_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _126_ (
    .A1(active_duty[0]),
    .A2(_057_),
    .ZN(_075_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _127_ (
    .A1(duty[0]),
    .A2(_056_),
    .A3(_062_),
    .ZN(_019_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _128_ (
    .A1(_075_),
    .A2(_019_),
    .B(rst),
    .ZN(_014_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _129_ (
    .A1(enable),
    .A2(_056_),
    .ZN(_020_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _130_ (
    .A1(duty[8]),
    .A2(_061_),
    .B(_056_),
    .C(enable),
    .ZN(_021_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _131_ (
    .A1(active_enable),
    .A2(_057_),
    .ZN(_022_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _132_ (
    .A1(_040_),
    .A2(_052_),
    .ZN(_023_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _133_ (
    .A1(active_duty[1]),
    .A2(counter[1]),
    .B(counter[0]),
    .C(active_duty[0]),
    .ZN(_024_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _134_ (
    .A1(_039_),
    .A2(_055_),
    .B(_024_),
    .ZN(_025_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _135_ (
    .A1(active_duty[2]),
    .A2(_054_),
    .B(_025_),
    .ZN(_026_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _136_ (
    .A1(active_duty[3]),
    .A2(_053_),
    .B1(_054_),
    .B2(active_duty[2]),
    .ZN(_027_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _137_ (
    .A1(active_duty[3]),
    .A2(_053_),
    .ZN(_028_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _138_ (
    .A1(_040_),
    .A2(_052_),
    .B1(_026_),
    .B2(_027_),
    .C(_028_),
    .ZN(_029_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _139_ (
    .A1(active_duty[5]),
    .A2(_051_),
    .B1(_023_),
    .B2(_029_),
    .ZN(_030_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _140_ (
    .A1(active_duty[6]),
    .A2(_050_),
    .B1(_051_),
    .B2(active_duty[5]),
    .ZN(_031_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _141_ (
    .A1(counter[7]),
    .A2(_048_),
    .Z(_032_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _142_ (
    .A1(active_duty[6]),
    .A2(_050_),
    .B1(_032_),
    .B2(active_duty[7]),
    .ZN(_033_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _143_ (
    .A1(_030_),
    .A2(_031_),
    .B(_033_),
    .ZN(_034_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _144_ (
    .A1(active_duty[7]),
    .A2(_032_),
    .B(active_duty[8]),
    .ZN(_035_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _145_ (
    .I(_035_),
    .ZN(_036_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _146_ (
    .A1(_034_),
    .A2(_036_),
    .B(active_enable),
    .C(_057_),
    .ZN(_037_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _147_ (
    .A1(_021_),
    .A2(_037_),
    .B(rst),
    .ZN(_015_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _148_ (
    .A1(_042_),
    .A2(_032_),
    .ZN(_016_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _149_ (
    .A1(active_duty[8]),
    .A2(_056_),
    .B(_042_),
    .ZN(_038_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _150_ (
    .A1(_073_),
    .A2(_038_),
    .ZN(_017_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _151_ (
    .A1(_020_),
    .A2(_022_),
    .B(rst),
    .ZN(_018_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _152_ (
    .CLK(clk),
    .D(_018_),
    .Q(active_enable)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _153_ (
    .CLK(clk),
    .D(_014_),
    .Q(active_duty[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _154_ (
    .CLK(clk),
    .D(_013_),
    .Q(active_duty[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _155_ (
    .CLK(clk),
    .D(_012_),
    .Q(active_duty[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _156_ (
    .CLK(clk),
    .D(_011_),
    .Q(active_duty[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _157_ (
    .CLK(clk),
    .D(_010_),
    .Q(active_duty[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _158_ (
    .CLK(clk),
    .D(_009_),
    .Q(active_duty[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _159_ (
    .CLK(clk),
    .D(_008_),
    .Q(active_duty[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _160_ (
    .CLK(clk),
    .D(_007_),
    .Q(active_duty[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _161_ (
    .CLK(clk),
    .D(_017_),
    .Q(active_duty[8])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _162_ (
    .CLK(clk),
    .D(_006_),
    .Q(counter[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _163_ (
    .CLK(clk),
    .D(_005_),
    .Q(counter[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _164_ (
    .CLK(clk),
    .D(_004_),
    .Q(counter[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _165_ (
    .CLK(clk),
    .D(_003_),
    .Q(counter[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _166_ (
    .CLK(clk),
    .D(_002_),
    .Q(counter[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _167_ (
    .CLK(clk),
    .D(_001_),
    .Q(counter[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _168_ (
    .CLK(clk),
    .D(_000_),
    .Q(counter[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _169_ (
    .CLK(clk),
    .D(_016_),
    .Q(counter[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _170_ (
    .CLK(clk),
    .D(_015_),
    .Q(pwm)
  );
endmodule
